services:
  - type: web
    name: esp32-iot-web
    env: node
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    autoDeploy: true

  - type: pgsql
    name: esp32-iot-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0 
        description: allow all
