services:
  - type: web
    name: esp32-iot
    env: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free

  - type: key-value
    name: esp32-redis
    plan: free

  - type: pgsql
    name: esp32-db
    plan: free
    ipAllowList: []
