services:
  - type: web
    name: esp32-dashboard
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true

  - type: pgsql
    name: esp32-db
    plan: free
    ipAllowList: []          # дозволяє доступ з твого web-сервісу
